version: "3.8"
services:
  db:
    image: postgres
    container_name: anuragpoc-postgres-server
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: anuragpoc
      POSTGRES_PASSWORD: anuragpoc1@
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: anuragpoc-pgadmin4-instance
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: abc@gmail.com
      PGADMIN_DEFAULT_PASSWORD: anuragpoc1@
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
