apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: keycloak
spec:
  type: NodePort
  selector:
    app: keycloak
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-deployment
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:latest
          resources:
            limits:
              cpu: "300m"
              memory: 256Mi
          args: ["start-dev"]
          env:
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgres-service.postgres-server.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: keycloak-db
            - name: DB_USER
              value: anuragpoc
            - name: DB_PASSWORD
              value: "anuragpoc1@"
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - containerPort: 8080
