try:
    dbutils.widgets.text("storageaccount", "","")
    dbutils.widgets.text("blobstorage", "","")
    dbutils.widgets.text("rootfilepath", "","")
    dbutils.widgets.text("storagekey", "","")
    dbutils.widgets.text("sourcename", "","")
    dbutils.widgets.text("parquet_storage_account", "","")
    dbutils.widgets.text("parquet_storage_container", "","")
    dbutils.widgets.text("parquet_storage_base_path", "","")
    dbutils.widgets.text("parquet_storage_key", "","")
    dbutils.widgets.text("akv_scope_name", "","")
    dbutils.widgets.text("idi_source_storageaccount", "","")
    dbutils.widgets.text("idi_source_storagecontainer", "","")
    dbutils.widgets.text("idi_outbound_storageaccount", "","")
    dbutils.widgets.text("idi_outbound_storagecontainer", "","")
    dbutils.widgets.text("fl_storageaccount", "","")
    dbutils.widgets.text("fl_storagecontainer", "","")
except Exception as e:
    dbutils.notebook.exit(f"Failure, Error occured while setting up the Widgets.\n{e}")