try:
    P_STORAGEACCOUNT = dbutils.widgets.get("storageaccount")
    P_BLOBSTORAGE = dbutils.widgets.get("blobstorage")
    P_ROOT_FILE_PATH = dbutils.widgets.get("rootfilepath")
    storagekey = dbutils.widgets.get("storagekey")
    P_SOURCE_NAME = dbutils.widgets.get("sourcename")
    PARQUET_STORAGE_ACCOUNT = dbutils.widgets.get("parquet_storage_account")
    PARQUET_STORAGE_CONTAINER = dbutils.widgets.get("parquet_storage_container")
    PARQUET_STORAGE_BASE_PATH = dbutils.widgets.get("parquet_storage_base_path")
    PARQUET_STORAGE_KEY = dbutils.widgets.get("parquet_storage_key")
    AKV_SCOPE_NAME = dbutils.widgets.get("akv_scope_name")
    P_IDI_SOURCE_STORAGEACCOUNT = dbutils.widgets.get("idi_source_storageaccount")
    P_IDI_SOURCE_STORAGECONTAINER = dbutils.widgets.get("idi_source_storagecontainer")
    P_IDI_OUTBOUND_STORAGEACCOUNT = dbutils.widgets.get("idi_outbound_storageaccount")
    P_IDI_OUTBOUND_STORAGECONTAINER = dbutils.widgets.get("idi_outbound_storagecontainer")
    P_FL_STORAGEACCOUNT = dbutils.widgets.get("fl_storageaccount")
    P_FL_STORAGECONTAINER = dbutils.widgets.get("fl_storagecontainer")
except Exception as e:
    dbutils.notebook.exit(f"Failure, Error occured while fetching widget data.\n{e}")