##-----Istio System Configuration-----##
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-system-01
  namespace: istio-system-01
spec:
  profile: default
  revision: "01"
  components:
    ingressGateways:
    - name: istio-ingressgateway
      label:
        istio: istio-ingressgateway-01
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-ipv4: x.x.x.x
    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 4Gi
  meshConfig:
    discoverySelectors:
      - matchLabels:
          istioenv: "01"
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    enableAutoMtls: true
    certificates:
    - secretName: <any-secret-name>
      dnsNames: [any-dns-name]
  values:
    global:
      istioNamespace: istio-system-01
      mountMtlsCerts: true
---