##-----Istio System Configuration-----##
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-system-app-2
  namespace: istio-app-2
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-ingressgateway-app-2
      enabled: true
      k8s:
        serviceAnnotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  revision: istio-app-2
  meshConfig:
    defaultConfig:
      holdApplicationUntilProxyStarts: true
    enableAutoMtls: true
    certificates:
    - secretName: <any-secret-name>
      dnsNames: [any-dns-name]
    discoverySelectors:
      - matchLabels:
          release: istio-app-2
  values:
    global:
      istioNamespace: istio-app-2
      mountMtlsCerts: true
    pilot:
      env:
        ENABLE_ENHANCED_RESOURCE_SCOPING: true