apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
  namespace: dev-01
spec:
  provider: azure
  secretObjects:
  - data:
    - key: Secret1
      objectName: Secret1
    secretName: akvsecret
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMMangedIdentity: "false"
    userAssignedIdentityID: ""
    keyvaultName: "abc-kv"
    objects: |
      array:
        - |
          objectName: Secret1
          objectType: secret
          objectVersion: ""
    tenantId: ""