apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: postgres-server
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: postgres-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: anuragpoc
            - name: POSTGRES_PASSWORD
              value: anuragpoc1@
            - name: POSTGRES_DB
              value: pgdb
          ports:
            - containerPort: 5432